### ISSUE TITLE
air factories needed on maps like Lava_Reef-V1

### ISSUE THREAD

**Issue by eronoobos** [eronoobos/BABAR-The-Shardifant#14]
It's a useful map to test the factory-choosing algorithm, because while all the metal spots are in places  kbots can _be_, only air units can _go_ to the other side of the map. I can't tell at a glance if the new factory-choosing algorithm in https://github.com/eronoobos/BABAR-The-Shardifant/pull/6 checks how many metal spots are in the relevant mobility network where it plans to build a factory. BestFactory used to do this, I believe. On Lava Reef, checking for that would reveal that a kbot factory would only provide access to less than half the metal spots.

**Comment by pandaro** [comment]
factory map choosing is at the first attempt, but for more clarification i will explain how it work now:
1 exclude map areas under the 20% of total area from possible location to build a factories
2 create table for each the mob area available where insert the builded factories
3 calculates the value for each mob area based on : relative dimension, relative mex number, geos and ai.mobRating
4 assign a value for each factories
 4.1 based on path rating for each units that a factory can build (if Shard LuaAI)
 4.2 based on mtype value for each units that a factory can build previous calculated in the mob area  system(point 3)
4.3 extra adjust factories values of hovercraft
5 all factories are insert in order of value in a table(ai.factoriesRanking)
6 take in order a factory from ai.factoriesRanking
7 if units can build
6 filter if there are a major reason to don't build it (example:need advance and this is not advanced)
7 search a position
8 filter if there already have a better factory in this position(mob area)
9 pass value to progress queue
10 eco, duplicate, location, gethelp filters(i think we need to modify this filters for factories)

this a explanation, i will test it on lot of map but i already see that are some problem to fix:
1 sometimes after first t2 factory, for example veh, instead build air water  or hover or other solution a lv1 builder start to build a kbot factory that cover the same area of the veh
2 when we have t2 level we need a way to build fast all the t2 level for each type of factory, for example water factory build t1 level and wait a lot to build the t2

feel free to manage what do you want regard the factory choosing system

**Comment by pandaro** [comment]
in lava ref there are a lot of economic problem

**Comment by eronoobos** [comment]
i believe this was addressed by https://github.com/eronoobos/BABAR-The-Shardifant/pull/23

**Comment by pandaro** [comment]
don't know dont test it atm
