### ISSUE TITLE
sometime builders don't respect the area reserved to the factories exit

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#27]
sometime builders don't respect the area reserved to the factories exit

**Comment by eronoobos** [comment]
do they build inside the factory exit reservation, or is the factory exit reservation placed on top of existing buildings? i was noticing this in my test games too, but i didn't notice which scenario happened

**Comment by pandaro** [comment]
a new build is placed inside the factory respect area

**Comment by pandaro** [comment]
after vars delocal all seems work fine
reopen if you notice problem

**Comment by eronoobos** [comment]
i still see this happening

**Comment by pandaro** [comment]
noooo
it seems ok few days ago...what happens again?

**Comment by eronoobos** [comment]
I'm pretty sure the problem was a last-ditch placement in LocationFilter that ignored buildsitehandler. It has been removed by https://github.com/eronoobos/BABAR-The-Shardifant/commit/6c60e23aece24a6853be6161d17d959fbe82d51a
