### ISSUE TITLE
cleanable buildings are built and then reclaimed

### ISSUE THREAD

**Issue by eronoobos** [eronoobos/BABAR-The-Shardifant#30]
There's nothing to prevent construction units from building energy buildings that will be considered cleanable and will be reclaimed.

**Comment by pandaro** [comment]
mainly is when we have a half metal and low Energy case, so t1 build Energy and turrets reclaim it.
My solution is don't clean if energy < 0.2
is better to prevent energy placing cause if we need energy is better do it

**Comment by pandaro** [comment]
can be close i think

**Comment by eronoobos** [comment]
new cleanhandler mostly fixes it
