### ISSUE TITLE
unnecessary cleaning

### ISSUE THREAD

**Issue by eronoobos** [eronoobos/BABAR-The-Shardifant#31]
Only things in the way should be cleaned. There's no need to reclaim potentially useful buildings that aren't obstructing anything. Simple way would be to only clean within a radius of a factory. Complicated way would be to look for nearby things to clean when a move order fails. (Complicated because I don't know if MoveOrderFailed even works.)

**Comment by pandaro** [comment]
if we need metal maybe reclaim all is usefull

**Comment by pandaro** [comment]
But keep some reserves of little production can save us if we take great damage in the center...
add label 'question' please is a gameplay type

**Comment by eronoobos** [comment]
> But keep some reserves of little production can save us if we take great damage in the center...

exactly

> if we need metal maybe reclaim all is usefull

since reclaimers have cleanables as targets, maybe just let them deal with non-obstructing cleanables

**Comment by eronoobos** [comment]
about MoveOrderFailed: it only works in non-lua, because (from [the wiki](https://springrts.com/wiki/Lua:Callins#Units))

> addon.UnitMoveFailed(???)
> ??? Not implemented in base handler

and indeed: `[f=-000001] Error: UpdateCallIn: UnitMoveFailed is not implemented`. why it's not implemented for spring's lua by default, i have no clue.

i could try to figure out how to implement it (aka prepare myself psychologically for a dev's irritation at being asked how to do so). or i could try to implement it myself, by keeping track of orders that have positions, and occasionally checking if the unit ever got to that position.

**Comment by eronoobos** [comment]
did my own custom implemtation by keeping track of orders https://github.com/eronoobos/ShardSpringLua/commit/ce4fc528ce0ec52faac14d06a3b6992ac51fec44

**Comment by eronoobos** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/commit/bcfe73076747dbdc80268d7a8c35c1c8e626369b

should probably allow mobile units to be cleaned, and clean them if their priority gets high enough (enough failed moves near them)

**Comment by pandaro** [comment]
noticed that now a builder reclaim wind after few minutes, but there was nothing of stuckked...
i will be check better

**Comment by eronoobos** [comment]
Yeah, the unitmovefailed recognition system isn't perfect. If you're going to look into it, I suggest setting `self.DebugEnabled = true` in cleanhandler's init, it will show when UnitMoveFailed triggers, and the priorities of cleanable buildings

**Comment by pandaro** [comment]
i check the system and is ok, if no reason persist i suggest close and reopen if need
