### ISSUE TITLE
(idea) delete ecohandler and put it into situation

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#39]
because economic data is a situation i suggest to move it in the new situation file

**Comment by eronoobos** [comment]
I named the module poorly, then. The move from taskqueues to situation was only because all that stuff in CheckForMapControl had no way to refer back to a module or behaviour. And because it was updated in an obscure and silly manner.

**Comment by pandaro** [comment]
we have already discuss over this,
no more reason to leave open
