### ISSUE TITLE
iterating on a table with keys that are tables

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#41]
as usual i will iterate on a table of table
but this time system say me:
`[f=0002600] Warning: Iterating a table with keys of type "table" in synced context!
stack traceback:`
is a insolvable problem?

**Comment by eronoobos** [comment]
Yes, Spring gadgets for some reason don't like iterating a table with keys that are tables. To be clear: iterating a table with _values_ that are tables, is fine. (I'm clarifying because "table of table" could also mean a table of values that are tables.)

**Comment by pandaro** [comment]
understood
