### ISSUE TITLE
Allow  low level factories to build if it is the top of the his mtype

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#44]
I noticed for air:
t1 airs factories don't build if there are for example t2 factory of bots
this is no good for me
maybe is better proportioning the [line](https://github.com/eronoobos/BABAR-The-Shardifant/blob/master/taskqueuebehaviour.lua#L610) in some cases.

**Comment by eronoobos** [comment]
i assumed this would be changed with factorybuildhandler

**Comment by pandaro** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/pull/63/commits/49767c1ebc6bc9e811412394bc8340cbd505cc98

**Comment by pandaro** [comment]
reopen if you think is the case
