### ISSUE TITLE
Error in shard loading

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#5]
just downloaded the engine version:101.0.1-418 direct from springlobby
put shard dev (not the LuaAI) ingame and try to start a battle, he give me this error:
`[f=-000001] Loading Skirmish AIs
[f=-000001] <SkirmishAI: Shard dev (team 0)>: ...e14 develop/AI/Skirmish/Shard/dev/ai/preload/api.lua:27: loop or previous error loading module 'taskqueuebehaviour'
stack traceback:
        [C]: ?
        [C]: ?
        [C]: in function 'require'
        ...e14 develop/AI/Skirmish/Shard/dev/ai/preload/api.lua:27: in function 'shard_include'
        ... develop/AI/Skirmish/Shard/dev/ai/BAR/behaviours.lua:1: in main chunk
        [C]: in function 'require'
        ...e14 develop/AI/Skirmish/Shard/dev/ai/preload/api.lua:27: in function 'shard_include'
        ...evelop/AI/Skirmish/Shard/dev/ai/behaviourfactory.lua:4: in main chunk
        [C]: in function 'require'
        ...e14 develop/AI/Skirmish/Shard/dev/ai/preload/api.lua:27: in function 'shard_include'
        ...408-g0e9ee14 develop/AI/Skirmish/Shard/dev/ai/ai.lua:2: in main chunk
[f=-000001] SkirmishAI (ID = 0, team ID = 0) is using cheats!
[f=-000001] ResourceMapAnalyzer by Krogothe, initialized for resource 0(Metal)
PANIC: unprotected error in call to Lua API (attempt to index a nil value)
terminate called recursively
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::condition_error> >'
  what():  boost::condition_variable::do_wait_until failed in pthread_cond_timedwait: Invalid argument
AL lib: (EE) alc_cleanup: 1 device not closed
`

and another problem:
in this version some commits seems lost, for example there are not all my task subfiles like taskeco, taskbuild etc, what i forget?

maybe this error is referred to this one: [issues 84](https://github.com/Tarendai/Shard/issues/84)

**Comment by eronoobos** [comment]
the spring engine just hasn't updated their version of Shard yet
https://github.com/spring/spring/tree/develop/AI/Skirmish
last update was 2 months ago

**Comment by pandaro** [comment]
ok
