### ISSUE TITLE
should never resurrect commanders

### ISSUE THREAD

**Issue by eronoobos** [eronoobos/BABAR-The-Shardifant#51]
it takes forever, and its metal is more useful than the unit when low on metal

same probably applies to krogoth, bantha, and anything else that takes a very long time to resurrect

**Comment by pandaro** [comment]
right

**Comment by eronoobos** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/commit/b3b8129f72e02d761aa2980a25e7712b6f8333da
https://github.com/eronoobos/BABAR-The-Shardifant/blob/e0aefafbf7c6457f7a7b34d0c7e9767f9b7dd07a/targethandler.lua#L597
