### ISSUE TITLE
fight strange bug

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#56]
i cannot describe as well this bug, but seems that:
1 bombers don't bomb at all, are always sleep at base
2 mobile units ignore enemy mobile units
at all i have the sensation of loose a lot of power in the war phase
excuse for not accurate description

**Comment by eronoobos** [comment]
1. i noticed this, too. could be because the bomber counter is hitting max?
2. i thought https://github.com/eronoobos/BABAR-The-Shardifant/commit/d77fb21f043b694db6df23d57b0bf6f09e31f170 fixed this, but i guess not. do you mean mobile units won't attack enemy mobile units, or mobile units won't defend against enemy mobile units?

**Comment by pandaro** [comment]
1 no, never bombing, when a lot, what is th max 16? ill test
2 seems not defense... but is heavy to understand, the behaviours add herself to other behaviours and all become confused

**Comment by eronoobos** [comment]
first i'm determining whether this is a ShardSpringLua bug or a bug with this config

**Comment by eronoobos** [comment]
this is strange, i remember testing very recently when bombers at least flew in circles around the base instead of just landing immediately and doing nothing. it must be a recent commit?

**Comment by eronoobos** [comment]
The bug may not be as strange as we thought. I fixed bomberbehaviour just by adding a `self.unit:ElectBehaviour()` where there was none. This makes me think that in the past, `ElectBehaviour()` was called every so often (five seconds, i think it was?). Behaviours were written with that assumption. I'm not sure why that is no longer true.

https://github.com/eronoobos/BABAR-The-Shardifant/commit/5fb30b4fa9778014a954d8b41f8affe9b05663f6

**Comment by eronoobos** [comment]
oh.
```
July 12, 2016

09:00 Pacific Daylight TimeWe're investigating delayed updates across the site.
```

**Comment by eronoobos** [comment]
if other units still seem to be acting weird, let me know

**Comment by eronoobos** [comment]
Since the bomber problem was solved I'm closing this. Perhaps the other issues you spoke of are https://github.com/eronoobos/BABAR-The-Shardifant/issues/59 ?
