### ISSUE TITLE
WARNING: bad taskque: corvp cannot build corseal

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#57]
noticed that factories sometime fail his taskqueue, dont know why

here full serie
`[f=0024197] WARNING: bad taskque: corvp cannot build corseal
[f=0024198] WARNING: bad taskque: corvp cannot build coracv
[f=0024199] WARNING: bad taskque: corvp cannot build correap
[f=0024514] WARNING: bad taskque: corvp cannot build cormex
[f=0024771] [InitOpenGL] video mode set to 1920x1080:24bit @60Hz 
[f=0024771] [InitOpenGL] video mode set to 1920x997:24bit @60Hz 
[f=0024771] [InitOpenGL] video mode set to 1920x1080:24bit @60Hz (windowed)
[f=0024771] [InitOpenGL] video mode set to 1920x1080:24bit @60Hz 
[f=0024776] Set view resolution: 1920 x 1080
[f=0024843] WARNING: bad taskque: corvp cannot build cormakr
^[[B[f=0025505] WARNING: bad taskque: corvp cannot build cormex
[f=0025507] WARNING: bad taskque: corvp cannot build corllt
[f=0025508] WARNING: bad taskque: corvp cannot build corrad
[f=0025834] WARNING: bad taskque: corvp cannot build cormex
[f=0027154] WARNING: bad taskque: corvp cannot build cormakr
[f=0027156] WARNING: bad taskque: corvp cannot build corllt
[f=0027157] WARNING: bad taskque: corvp cannot build hllt
[f=0027159] WARNING: bad taskque: corvp cannot build corrad
[f=0027162] WARNING: bad taskque: corvp cannot build corhlt
[f=0027163] WARNING: bad taskque: corvp cannot build corpun
`

**Comment by eronoobos** [comment]
seems like it's getting some kind of combat engineer taskqueue?

**Comment by pandaro** [comment]
no, coracv is not buildable by engineer

**Comment by eronoobos** [comment]
wtf did i do

**Comment by eronoobos** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/commit/e9032a28557cd85be46e3b459b49bc445e85656d
