### ISSUE TITLE
sometimes builds advanced air factory before building advanced vehicle or kbot

### ISSUE THREAD

**Issue by eronoobos** [eronoobos/BABAR-The-Shardifant#58]
Building an air factory can be a strategy, but it seems very common that on a primarily kbot or vehicle map, an air factory will be built before a level 2 kbot or vehicle factory. It gives the AI one nice sneaky bombing run, but otherwise slows it down a lot (takes more time to get to lvl2 and get moho mexes, builds slow-building air construction units, builds many lvl1 air units that after the first bombing run will mostly just be shot down).

Building an air factory on a map where it's not needed needs to be decided strategically somehow, or not done at all.

**Comment by eronoobos** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/commit/c3dac9bcb2c9d68f94ca32d5223d29250dca3e5b may prevent building air factories before lvl2 of other already build factories

edit: nope, still does it

**Comment by eronoobos** [comment]
more dire than building an air factory is never building a lvl2 factory. have no idea why this happens

**Comment by pandaro** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/pull/71/commits/92a7e640cc43399b6093447ed8abd2696b572246
and 
https://github.com/eronoobos/BABAR-The-Shardifant/pull/71/commits/78190e778ed5df538e263ddb685d8c482364e261
will be fix

**Comment by pandaro** [comment]
i think can be closed and reopened if bad behaviour re com

**Comment by eronoobos** [comment]
this still happens. it will build an advanced non-air factory eventually, but it takes a long time. i think this is happening because air factories are the easiest to find locations for (they don't need exit lanes). need to look more thoroughly for a factory location before giving up.

**Comment by pandaro** [comment]
mmm ok

**Comment by eronoobos** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/commit/2aba7eb8a941efbf1aa95763794e276181f8bca5
https://github.com/eronoobos/BABAR-The-Shardifant/commit/317ced1ddc882ea6bdbe0021e8ac53af56389848
https://github.com/eronoobos/BABAR-The-Shardifant/commit/ff9816451b24c215eb2a987839a6c24a40422fe0
