### ISSUE TITLE
Advanced economy is builded far away from center

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#64]
i noticed that frequently t2 economy is build far away from the factory and then in dangerous position,
i suggest to reduce this behavior a bit

**Comment by eronoobos** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/commit/6c60e23aece24a6853be6161d17d959fbe82d51a + https://github.com/eronoobos/BABAR-The-Shardifant/commit/ed59e99aacf2a6147340455fd2aecba39d7a05cd should help. Buildings that cost more now have a higher cutoff distance, above which builders ignore turtle placement.

**Comment by pandaro** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/pull/71/commits/e47ab1b565daec8d692de646ca1120407ff39e77

this help by searching for ground adv eco near nanoturrets

**Comment by eronoobos** [comment]
added nanohandler, and now adv eco builds in nano overlapping spots if possible. situation seems much improved
