### ISSUE TITLE
nano freez after cleaning process

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#7]
sometime the nano stop to work after clean stuff

**Comment by pandaro** [comment]
in fact:
sometime a nano clean something, after this he stuck itself, if another unit clean something else, the first unit will be unstuck

**Comment by eronoobos** [comment]
i think it has to do with assistbehaviour failing to re-activate for some reason. assistbehaviour is what gives the nanoturret the patrol order that keeps it doing things

**Comment by pandaro** [comment]
i know assistbehavoiur...

**Comment by eronoobos** [comment]
and assistbehaviour isn't reactivating because cleanerbehaviour isn't deactivating. possibly because the cleanable unit is never removed from the table of cleanables? am attempting to debug this. https://github.com/eronoobos/BABAR-The-Shardifant/issues/9 makes me distrust that behaviours are even doing what i expect them to be doing

**Comment by eronoobos** [comment]
just a note to myself, cleanerbehaviour and cleanhandler use `UnitDestroyed` callins, which do nothing. it should be `UnitDead`. but what's inside the callin causes errors, need to fix it

**Comment by pandaro** [comment]
im online if you need, in #badev channel

**Comment by pandaro** [comment]
> use UnitDestroyed callins
> why you should use this? instead unit dead?

**Comment by eronoobos** [comment]
other way around, currently they use `UnitDestroyed`, but should use `UnitDead`.
`UnitDead` is the callin for Shard modules & behaviours
`UnitDestroyed` is the callin for Spring gadgets & widgets (which is why I got confused)

**Comment by eronoobos** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/commit/6c600162002d29df1cd60c6b1559ca0fa78b13d0 fixes it, but i'll test it to make sure
