### ISSUE TITLE
recursion not permitted

### ISSUE THREAD

**Issue by pandaro** [eronoobos/BABAR-The-Shardifant#82]
[f=0026760] Error: LuaRules::RunCallIn: error = 2, UnitIdle, [Internal Lua error: Call failure] [string "luarules/gadgets/ai/preload/spring_lua/unit..."]:225: GiveOrderToUnit() recursion is not permitted
stack traceback:
    [C]: in function 'GiveOrderToUnit'
    [string "luarules/gadgets/ai/preload/spring_lua/unit..."]:225: in function 'ExecuteCustomCommand'
    [string "luarules/gadgets/ai/BAR/attackerbehaviour.l..."]:156: in function 'SetMoveState'
    [string "luarules/gadgets/ai/BAR/attackerbehaviour.l..."]:77: in function 'Activate'
    [string "luarules/gadgets/ai/unit.lua"]:151: in function 'ElectBehaviour'
    [string "luarules/gadgets/ai/BAR/defendbehaviour.lua"]:74: in function 'OwnerIdle'
    [string "luarules/gadgets/ai/unit.lua"]:97: in function 'UnitIdle'
    [string "luarules/gadgets/ai/unithandler.lua"]:118: in function 'v'
    [string "luarules/gadgets/ai/ai.lua"]:178: in function 'UnitIdle'
    [string "luarules/gadgets/ai/ai.lua"]:118: in function 'UnitIdle'
    [string "LuaRules/Gadgets/ailoader.lua"]:323: in function 'UnitIdle'
    ...
    [C]: in function 'GiveOrderToUnit'
    [string "luarules/gadgets/ai/preload/spring_lua/unit..."]:107: in function 'Move'
    [string "luarules/gadgets/ai/BAR/defendbehaviour.lua"]:124: in function 'Update'
    [string "luarules/gadgets/ai/unit.lua"]:28: in function 'Update'
    [string "luarules/gadgets/ai/unithandler.lua"]:30: in function 'v'
    [string "luarules/gadgets/ai/ai.lua"]:178: in function 'Update'
    [string "luarules/gadgets/ai/ai.lua"]:52: in function 'Update'
    [string "LuaRules/Gadgets/ailoader.lua"]:249: in function 'GameFrame'
    [string "LuaRules/gadgets.lua"]:877: in function <[string "LuaRules/gadgets.lua"]:875>
    (tail call): ?

**Comment by eronoobos** [comment]
Oops, yes, this is the problem with using Idle to time unit movement. I'll fix it by delaying the movement to next frame.

**Comment by eronoobos** [comment]
https://github.com/eronoobos/BABAR-The-Shardifant/commit/a3a0b3187c33c090cbceaf70014086a29b8ce18c
